### ISSUE TITLE
Исправить коллизии и y-sorting

### ISSUE THREAD

**Issue by PuzyrevHarkovskii** [kashandra1/Godot-Progame#2]
С коллизиями и y-sorting (чтобы можно было заходить за объекты) проблема. 

1. Деревья у бассейна со всех сторон непроходимые - их нужно в наборе тайлов в один тайл собрать и проставить коллизию и центры координат 
2. Сухие кусты в пустые тоже (их нужно на слой "trees" - он у нас с y-sorting)

**Comment by kashandra1** [comment]
Сделал
